[tool.poetry]
name = "realmsoar"
version = "0.1.0"
description = ""
authors = ["Kevin McManus <kmcmanus98035@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
mkdocs = "^1.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
